// <auto-generated />
namespace Demo_MVC_CRUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NewModel_Author : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewModel_Author));
        
        string IMigrationMetadata.Id
        {
            get { return "202011090749486_NewModel_Author"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
